### ISSUE TITLE
Fix Test Async behaviour

### ISSUE THREAD

**Issue by CjHare** [windranger-io/solidity-project-template#29]
Intermittent test failure for GitHub action

```
Run npm test

> solidity-project-template@0.0.3 test /home/runner/work/solidity-project-template/solidity-project-template
> mocha --exit --recursive --require ts-node/register 'test/**/*.test.ts'



  BitDAO token contract
    1) "before all" hook for "name is BitDAO"


  0 passing (2s)
  1 failing

  1) BitDAO token contract
       "before all" hook for "name is BitDAO":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/solidity-project-template/solidity-project-template/test/bitdao.test.ts)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
```

**Comment by CjHare** [comment]
Dependatbot PRs now consistently pass the test.
